<script setup lang="ts">
  import Card from '../components/Card.vue'
</script>

<template>
  <div id="about-wrapper">
    <Card head='Origins' body='The furthest back I can remember writing a line of code is in tenth grade. My journey into the wide world of programming began in early 2018, while I was living in downtown Toronto and attending Centennial College for Music Industry Arts & Performance. Nullam ornare lacinia ante sed vehicula. Curabitur convallis gravida metus, congue dictum tellus rutrum non. Sed commodo libero ut porta tristique. Aliquam ac leo commodo ligula sagittis ornare et nec nunc. Integer ipsum nisi, volutpat ac porta ac, fermentum tincidunt nulla. Nunc gravida dolor nunc, ut hendrerit nulla fringilla in. Ut venenatis, risus quis volutpat malesuada, diam nulla malesuada lorem, consequat pretium turpis tortor a nibh. Sed dui nibh, molestie in risus non, laoreet cursus ante. Aliquam aliquet vel massa at faucibus. Nam interdum venenatis neque, at vestibulum ligula rhoncus nec.'/>
    <Card head='Education' body='Unsure of where to head next, I first committed myself to collecting the high school credits I needed in order to apply to university ("Advanced Functions" + "Calculus and Vectors"). Over the course of a year I commenced and completed these two courses and then applied to Business at the University of Guelph.In the fall of 2019 I enrolled in Business; that semester, curiously I enrolled in an elective course called "Introduction to Programming". Curabitur convallis gravida metus, congue dictum tellus rutrum non. Sed commodo libero ut porta tristique. Aliquam ac leo commodo ligula sagittis ornare et nec nunc. Integer ipsum nisi, volutpat ac porta ac, fermentum tincidunt nulla. Nunc gravida dolor nunc, ut hendrerit nulla fringilla in. Ut venenatis, risus quis volutpat malesuada, diam nulla malesuada lorem, consequat pretium turpis tortor a nibh. Sed dui nibh, molestie in risus non, laoreet cursus ante. Aliquam aliquet vel massa at faucibus. Nam interdum venenatis neque, at vestibulum ligula rhoncus nec. Nam porttitor, erat semper aliquet rutrum, velit justo maximus metus, consectetur imperdiet odio est quis magna. Curabitur fringilla quam non velit molestie, non tincidunt lacus varius. Ut ut enim venenatis, consectetur mi et, suscipit odio. In quam metus, ultricies in ipsum ac, ornare consequat nisl. Pellentesque pharetra, magna sed bibendum eleifend, augue lectus pellentesque sapien, sit amet lacinia lorem ligula a enim. Phasellus vitae ante at elit pharetra convallis. Donec iaculis non felis at eleifend. Proin non tortor posuere, commodo lorem ut, cursus turpis. Sed enim erat, elementum eu metus vitae, elementum elementum sem.'/>
    <Card head="Prospects" body="From here, there are a multitude of things I want to accomplish. Nullam ornare lacinia ante sed vehicula. Curabitur convallis gravida metus, congue dictum tellus rutrum non. Sed commodo libero ut porta tristique. Aliquam ac leo commodo ligula sagittis ornare et nec nunc. Integer ipsum nisi, volutpat ac porta ac, fermentum tincidunt nulla. Nunc gravida dolor nunc, ut hendrerit nulla fringilla in. Ut venenatis, risus quis volutpat malesuada, diam nulla malesuada lorem, consequat pretium turpis tortor a nibh. Sed dui nibh, molestie in risus non, laoreet cursus ante. Aliquam aliquet vel massa at faucibus. Nam interdum venenatis neque, at vestibulum ligula rhoncus nec. Nam porttitor, erat semper aliquet rutrum, velit justo maximus metus, consectetur imperdiet odio est quis magna. Curabitur fringilla quam non velit molestie, non tincidunt lacus varius. Ut ut enim venenatis, consectetur mi et, suscipit odio. In quam metus, ultricies in ipsum ac, ornare consequat nisl. Pellentesque pharetra, magna sed bibendum eleifend, augue lectus pellentesque sapien, sit amet lacinia lorem ligula a enim. Phasellus vitae ante at elit pharetra convallis. Donec iaculis non felis at eleifend. Proin non tortor posuere, commodo lorem ut, cursus turpis. Sed enim erat, elementum eu metus vitae, elementum elementum sem.Etiam pharetra consectetur quam, sed mollis ex tristique ac. Fusce rutrum vitae orci eget dapibus. In vitae diam odio. Sed et sagittis neque. Nunc vitae diam vestibulum, laoreet arcu a, laoreet dui. Mauris congue mauris eleifend, viverra neque id, pretium leo. Sed egestas faucibus diam, ac gravida velit euismod a. Vestibulum porta vulputate nisi ac tempus. Donec pulvinar, purus et venenatis sagittis, risus ligula mollis nisi, at bibendum nulla justo hendrerit augue. Mauris ornare aliquet diam, sed blandit tortor. Aenean vehicula mauris sed sem tincidunt rhoncus. Finally, I am interested in using programming as a means for communicating climate-related data to the broader public in order to spread and validate the important findings produced by climate scientists."/>
  </div>
</template>
