# Generated by Django 4.0.4 on 2022-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_brief_tag_rename_content_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='topic',
            field=models.CharField(max_length=9),
        ),
    ]
