# Generated by Django 4.0.4 on 2022-05-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_brief_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='html',
            new_name='content',
        ),
        migrations.AddField(
            model_name='brief',
            name='content',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brief',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
