# Generated by Django 4.0.4 on 2022-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_rename_html_project_content_brief_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(to='server.project'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='keyword',
            field=models.CharField(max_length=25),
        ),
    ]
