# Generated by Django 4.0.4 on 2022-05-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tag_projects_alter_tag_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(related_name='tags', to='server.project'),
        ),
    ]
