# Generated by Django 4.1.7 on 2023-04-30 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_tag_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brief',
            new_name='About',
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 29)),
        ),
    ]
